---
title: "Zscores2015"
author: "SM"
date: "December 4, 2017"
output: html_document
---

```{r}
require(knitr)
library(readr)
library(tidyverse)
library(plyr)
```

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
opts_knit$set(root.dir = "C:/Users/Sohini Mukherjee/OneDrive/Documents/Harvard University/Academic/Fall 2017/BST 260 - Data Science I/Homework/ds-proj_pull")
getwd()
```

```{r}
RWJFMeasures_2015 <- read.csv("C:/Users/Sohini Mukherjee/OneDrive/Documents/Harvard University/Academic/Fall 2017/BST 260 - Data Science I/Final Project/RWJF/zscores/IV_2014_healthrank.csv")
str(RWJFMeasures_2015)
```

```{r}
names(RWJFMeasures_2015)[names(RWJFMeasures_2015) == 'ï..FIPS'] <- 'FIPS'
RWJFMeasures_2015$HO_rank <- as.numeric(as.character(RWJFMeasures_2015$HO_rank))
RWJFMeasures_2015$HF_rank <- as.numeric(as.character(RWJFMeasures_2015$HF_rank))
RWJFMeasures_2015$MORT_rank <- as.numeric(as.character(RWJFMeasures_2015$MORT_rank))
RWJFMeasures_2015$MORB_rank <- as.numeric(as.character(RWJFMeasures_2015$MORB_rank))
RWJFMeasures_2015$HB_rank <- as.numeric(as.character(RWJFMeasures_2015$HB_rank))
RWJFMeasures_2015$CC_rank <- as.numeric(as.character(RWJFMeasures_2015$CC_rank))
RWJFMeasures_2015$SE_rank <- as.numeric(as.character(RWJFMeasures_2015$SE_rank))
RWJFMeasures_2015$PE_rank <- as.numeric(as.character(RWJFMeasures_2015$PE_rank))
```


```{r}
str(RWJFMeasures_2015)
```

```{r}
RWJFMeasures_2015$HO_rank <- ave(RWJFMeasures_2015$HO_rank, RWJFMeasures_2015$State, FUN=scale)

```

Get zscores
```{r}
RWJFMeasures_2015$HF_rank <- ave(RWJFMeasures_2015$HF_rank, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$MORT_rank <- ave(RWJFMeasures_2015$MORT_rank, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$MORB_rank <- ave(RWJFMeasures_2015$MORB_rank, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$HB_rank <- ave(RWJFMeasures_2015$HB_rank, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$CC_rank <- ave(RWJFMeasures_2015$CC_rank, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$SE_rank <- ave(RWJFMeasures_2015$SE_rank, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$PE_rank <- ave(RWJFMeasures_2015$PE_rank, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015 <- add_column(RWJFMeasures_2015, deaths_zscore="Deaths", .after = "Deaths")
RWJFMeasures_2015 <- add_column(RWJFMeasures_2015, pop_zscore="Population", .after = "Population")
RWJFMeasures_2015$deaths_zscore <- ave(RWJFMeasures_2015$Deaths, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$pop_zscore <- ave(RWJFMeasures_2015$Population, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$YPPL_rate <- ave(RWJFMeasures_2015$YPPL_rate, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$Fair_percent <- ave(RWJFMeasures_2015$Fair_percent, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$PPH_days <- ave(RWJFMeasures_2015$PPH_days, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$PMH_days <- ave(RWJFMeasures_2015$PMH_days, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$LBW_percent <- ave(RWJFMeasures_2015$LBW_percent, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$smoking_percent <- ave(RWJFMeasures_2015$smoking_percent, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$Obese_percent <- ave(RWJFMeasures_2015$Obese_percent, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$FoodEnv_Index <- ave(RWJFMeasures_2015$FoodEnv_Index, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$inactive_percent <- ave(RWJFMeasures_2015$inactive_percent, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$Exercise_access_percent <- ave(RWJFMeasures_2015$Exercise_access_percent, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$Binge_percent <- ave(RWJFMeasures_2015$Binge_percent, RWJFMeasures_2015$State, FUN=scale)
```

```{r}
RWJFMeasures_2015$CHL_100000 <- ave(RWJFMeasures_2015$CHL_100000, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$TeenB_rate <- ave(RWJFMeasures_2015$TeenB_rate, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$Uninsure_percent <- ave(RWJFMeasures_2015$Uninsure_percent, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$PCP_rate <- ave(RWJFMeasures_2015$PCP_rate, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$dentist_rate <- ave(RWJFMeasures_2015$dentist_rate, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$MHP_rate <- ave(RWJFMeasures_2015$MHP_rate, RWJFMeasures_2015$State, FUN=scale)

RWJFMeasures_2015$hbac_rate <- ave(RWJFMeasures_2015$hbac_rate, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$mammo_percent <- ave(RWJFMeasures_2015$mammo_percent, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$Hsgrad_rate <- ave(RWJFMeasures_2015$Hsgrad_rate, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$college_percent <- ave(RWJFMeasures_2015$college_percent, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$unemploy_rate <- ave(RWJFMeasures_2015$unemploy_rate, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$Childpov_percent <- ave(RWJFMeasures_2015$Childpov_percent, RWJFMeasures_2015$State, FUN=scale)

RWJFMeasures_2015$singleparent_percent <- ave(RWJFMeasures_2015$singleparent_percent, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$social_assoc_rate <- ave(RWJFMeasures_2015$social_assoc_rate, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$violentcrime_rate <- ave(RWJFMeasures_2015$violentcrime_rate, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$airpollution <- ave(RWJFMeasures_2015$airpollution, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$drinkingwater_viol <- ave(RWJFMeasures_2015$drinkingwater_viol, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$severehousing_percent <- ave(RWJFMeasures_2015$severehousing_percent, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$driving_alone_percent <- ave(RWJFMeasures_2015$driving_alone_percent, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$longcommute_percent <- ave(RWJFMeasures_2015$longcommute_percent, RWJFMeasures_2015$State, FUN=scale)
```


```{r}
RWJFMeasures_2015$acscrate <- ave(RWJFMeasures_2015$acscrate, RWJFMeasures_2015$State, FUN=scale)
RWJFMeasures_2015$injurydeathrate <- ave(RWJFMeasures_2015$injurydeathrate, RWJFMeasures_2015$State, FUN=scale)
```


Mistake made - use for 2014 data
```{r}
RWJFMeasures_2014 <- RWJFMeasures_2015
```




```{r}
save(RWJFMeasures_2014, file = "C:/Users/Sohini Mukherjee/OneDrive/Documents/Harvard University/Academic/Fall 2017/BST 260 - Data Science I/Homework/ds-proj_pull/Measures_2014_Z-scores.Rda")
```




