---
title: "Plots"
author: "SM"
date: "December 9, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(fiftystater)
library(mapproj)
library(gridExtra)
library(RColorBrewer)
library(readr)
library(stringr)
```

```{r}
data("fifty_states")
ledata$state <- sapply(ledata$state, tolower)
```

```{r}
map_2010_2 <- ledata %>%
    filter( state!="united states") %>%
    select( state, change )
  ggplot(ledata, aes(map_id = state)) + 
    geom_map(aes(fill = change), map = fifty_states) + 
    expand_limits(x = fifty_states$long, y = fifty_states$lat) +
    coord_map() +
    scale_x_continuous(breaks = NULL) + 
    scale_y_continuous(breaks = NULL) +
    labs(x = "", y = "") +
    theme(legend.position = "bottom", 
        panel.background = element_blank()) +
    scale_fill_gradientn(colors=rev(colorRampPalette(colors=c("red", "white", "blue"))(1000)))
  
map_2010_2
```



```{r}
plotmxForYear <- function(map){
  per_state_mx <- ledata %>%
    filter( state!="united states") %>%
    select( state, change )
  ggplot(per_state_mx, aes(map_id = state)) + 
    geom_map(aes(fill = change), map = fifty_states) + 
    expand_limits(x = fifty_states$long, y = fifty_states$lat) +
    coord_map() +
    scale_x_continuous(breaks = NULL) + 
    scale_y_continuous(breaks = NULL) +
    labs(x = "", y = "") +
    theme(legend.position = "bottom", 
        panel.background = element_blank()) +
  scale_fill_gradient(low="pink", high="red", na.value="grey50", breaks=seq(min(ledata$change), max(ledata$change), by=100)) +
  theme(legend.position = "bottom", 
        panel.background = element_blank())}

plotmxForYear(map)
```

