---
title: "exploratory_Alex"
author: "alex"
date: "11/29/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(ggthemes)
library(gridExtra)
```

## general analysis

Lowest LE
```{r}
tail(sort(ledata$LE2014, decreasing = TRUE), 5)
```

```{r}
which(ledata$LE2014 == 66.81)
```

```{r}
ind <- order(ledata$LE2014) 
ledata$county[ind] 
ledata$state[ind]
```

lowest le change:
```{r}
ind <- order(ledata$change) 
ledata$county[ind] 
ledata$state[ind]
ledata$change[ind]
```

avg change in states 
```{r}
ledata2 <- ledata %>% group_by(state) %>%
     summarize(mean_change = mean(change),
               sd_change = sd(change),
               n = n()) 
```

drop state summary observation
```{r}
ledata2 <- ledata2[-c(52:103), ]
```


which state has avg lowest change
```{r}
ind <- order(ledata2$mean_change) 
ledata2$state[ind] 
ledata2$mean_change[ind]
```

only looking at state avg change in le 
```{r}
lestate <- lestate[!grepl(c("County", "Area", "Municipality", "Borough", "Parish", "City"), lestate$county),]
lestate <- lestate[!grepl("Area", lestate$county),]
lestate <- lestate[!grepl("Municipality", lestate$county),]
lestate <- lestate[!grepl("Borough", lestate$county),]
lestate <- lestate[!grepl("Parish", lestate$county),]
lestate <- lestate[!grepl("City", lestate$county),]
lestate <- filter(ledata, county)
ind <- order(ledata2$mean_change) 
ledata2$state[ind] 
ledata2$mean_change[ind]
```
drop DC dublicate
```{r}
lestate <- lestate[-c(330), ]
```

find lowest state
```{r}
ind <- order(lestate$change) 
lestate$state[ind] 
lestate$change[ind]
```



Cause of death in 2010
```{r}
bothmortality <- filter(AllMortality, sex_id == 3) 

p2 <- ggplot(data = bothmortality, aes(cause_id, year_id)) 
p2 + geom_point()

mort2010 <- filter(bothmortality, year_id == 2010)
p1 <- ggplot(data = mort2010, aes(cause_id))
p1 + geom_histogram()
```

HIV/AIDS/TB death across years

```{r}
hivaids <- filter(bothmortality, cause_id == 296)
p2 <- ggplot(data = hivaids, aes(year_id)) 
p2 + geom_histogram(bins = 30)
```

Reduced All Cause by state
```{r}
bothstate <- filter(state_mortality, sex_id == 3)
allcause <- filter(bothstate, cause_id == 294)

allcause <- allcause %>% group_by(location_id, region, year_id, state, abb) %>%
     summarize(mean_mx = mean(mx),
               sd_mx = sd(mx),
               n = n()) 

p3 <- ggplot(data = allcause, aes(region, mean_mx)) 
p3 + geom_point()
```

Breakdown by year
```{r}
g <- allcause %>% filter(year_id == 2010) %>%
  group_by(year_id) %>%
  ggplot(aes(region, mean_mx)) + 
  geom_point() +
  xlab("Region") +
  ylab("Mean All-Cause Mortality") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

h <- allcause %>% filter(year_id == 2011) %>%
  group_by(year_id) %>%
  ggplot(aes(region, mean_mx)) + 
  geom_point() +
  xlab("Region") +
  ylab("Mean All-Cause Mortality") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

i <- allcause %>% filter(year_id == 2012) %>%
  group_by(year_id) %>%
  ggplot(aes(region, mean_mx)) + 
  geom_point() +
  xlab("Region") +
  ylab("Mean All-Cause Mortality") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

k <- allcause %>% filter(year_id == 2013) %>%
  group_by(year_id) %>%
  ggplot(aes(region, mean_mx)) + 
  geom_point() +
  xlab("Region") +
  ylab("Mean All-Cause Mortality") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

z <- allcause %>% filter(year_id == 2014) %>%
  group_by(year_id) %>%
  ggplot(aes(region, mean_mx)) + 
  geom_point() +
  xlab("Region") +
  ylab("Mean All-Cause Mortality") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
grid.arrange(g, h, i, k, z)
```

Reduced to South - looking at cause of death
```{r}
bothstate <- filter(state_mortality, sex_id == 3)
southmort <- filter(bothstate, region == "South")

southmort <- southmort %>% group_by(cause_id, cause_name, location_id, region, year_id, state, abb) %>%
     summarize(mean_mx = mean(mx),
               sd_mx = sd(mx),
               n = n()) 
```



```{r}

```

