---
title: "Exploratory Data Analysis"
author: "HOJ"
date: "11/20/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(broom)
library(ggplot2)
library(maps)
library(rgdal)
```

## Preliminary Exploratory Analysis (pre master merge/cleaning)

```{r EDA}
## starting to look at what was posted this weekend 

load("~/Desktop/HSPH/BST260/FinalProject/AllMortality.Rda")
load("~/Desktop/HSPH/BST260/FinalProject/Predictors_1.Rda")
load("~/Desktop/HSPH/BST260/FinalProject/Race.Rda")

install.packages("noncensus") ## exploring a package using census data 
library(noncensus)

summary(IV)
summary(AllMortality)
summary(Race)

levels(AllMortality$cause_name)

AllMortality %>% filter(year_id == 2010) %>%
        group_by(cause_name) %>% ggplot() + geom_boxplot()

AllMortality %>% group_by(location_id) %>% ggplot() + geom_point(aes(cause_name, lower))
```

## Joining AllMortality, IV, and Race by FIPS
```{r}
identical(IV$FIPS, Race$FIPS) 
#not identical - is this a problem or just reflecting some anticipated missingness? 

IV_Race <- left_join(Race, IV, by = "FIPS")

AllMortality_mod <- AllMortality %>% mutate_if(is.character, as.integer) ## changing FIPS to integer object class to be able to merge

All_Merge <- left_join(IV_Race, AllMortality_mod, by = "FIPS") ## master data set with all covariates/outcomes 
```

## US County Map Code Tools
```{r}
## useful: http://mgimond.github.io/ES218/Week12a.html

# Load the county data from the maps package
cnty <- map_data("county")

# Plot the counties
ggplot(cnty, aes(long,lat, group = group)) + 
  geom_polygon(aes(fill = region), colour = rgb(1,1,1,0.2)) + 
  theme(legend.position="none") +
  coord_quickmap()

## Removing background grid
ggplot(cnty, aes(long,lat, group = group)) + 
  geom_polygon(aes(fill = region), show.legend = FALSE, colour = rgb(1,1,1,0.2)) + 
  coord_map("bonne",  param=45) +
  theme_void()

cnty2 <- cnty %>%
        mutate(polyname = paste(region,subregion,sep=",")) %>%
        left_join(county.fips, by="polyname")

tmp <- tempdir()
link <- "http://www2.census.gov/geo/tiger/GENZ2010/gz_2010_us_050_00_20m.zip"
filename <- basename(link)
download.file(link, filename)
unzip(filename, exdir = tmp )
shapefile <- readOGR( dsn=tmp, layer = tools::file_path_sans_ext(filename) )

shapefile$FIPS <- as.numeric(substr(shapefile$GEO_ID, 10, 14))
shapefile$id   <- rownames(shapefile@data)

cnty2 <- fortify(shapefile, id="id")

cnty2.cs <- cnty2 %>%
            inner_join(shapefile@data, by="id") %>%
            inner_join(df1, by="FIPS")
```
