---
title: "R Notebook"
output: html_notebook
---


```{r}

#ADD REGION INFO

library(stringr)
library(noncensus)
library(tidyverse)
library(dslabs)
library(ggplot2)
library(dplyr)
library(ggthemes)
library(ggrepel)
library(RColorBrewer)
data(murders)


load("~/Documents/Fall2017/BST260/FinalProject/ds-proj/Age.Rda")
load("~/Documents/Fall2017/BST260/FinalProject/ds-proj/AllMortality.Rda")
load("~/Documents/Fall2017/BST260/FinalProject/ds-proj/Race.Rda")
load("~/Documents/Fall2017/BST260/FinalProject/ds-proj/Predictors_1.Rda")


Race$FIPS <- str_pad(Race$FIPS, width=5, side="left", pad="0")
IV$FIPS <- str_pad(IV$FIPS, width=5, side="left", pad="0")

stateinfo <- murders %>% select(region, state, abb)

IV_Race <- left_join(Race, IV, by = "FIPS")
IV_Race <- left_join(IV_Race, Age, by = "FIPS")
names(IV_Race)[2] <- tolower(names(IV_Race)[2])
names(IV_Race)[10:11] <- tolower(names(IV_Race)[10:11])

#we need to remove state mortality rates into another data frame
AllMortality$FIPS <- as.numeric(as.character(AllMortality$FIPS)) 
#sorry this gets rid of 0 padding
IV_Race$FIPS <- as.numeric(as.character(IV_Race$FIPS))


state_mortality <- AllMortality %>% filter(FIPS<=00056)
names(state_mortality )[names(state_mortality ) == 'location_name'] <- 'state'


county_mortality <- AllMortality %>% filter(FIPS>00056)
names(county_mortality )[names(county_mortality ) == 'location_name'] <- 'county'


#now we are working with state mortality, county mortality, and county variables for race and health risks
stateinfo_ivrace <- IV_Race %>% select(county_state, county, state, FIPS)
stateinfo_ivrace$state <- as.character(as.factor(stateinfo_ivrace$state)) 
state_mortality$state <- as.character(as.factor(state_mortality$state)) 
# makes 'state' a character class so it merges

stateinfo <- left_join(stateinfo, stateinfo_ivrace , by = "state") #combine all geo info
stateinfo <- stateinfo %>% distinct(region, abb, state, county_state, county, FIPS)

countyinfo <- stateinfo[c(1, 3, 2, 5, 4, 6)] #reorder
IVinfo <- stateinfo[c("region","FIPS")]
stateinfo <- stateinfo[c("region","abb","state")]


county_mortality <- left_join(county_mortality, countyinfo, by = "FIPS")
state_mortality <- left_join(state_mortality, stateinfo, by = "state")
IV_Race <- left_join(IV_Race, IVinfo, by = "FIPS")

save(county_mortality, file="county_mortality-EG.Rda")
save(state_mortality, file="state_mortality-EG.Rda")
save(IV_Race, file="IV_Race-EG.Rda")
class(state_mortality$year_id)

```

EXPLORATORY ANALYSIS
```{r}
state_mortality %>% filter(cause_name == "All causes") %>% ggplot() %>% geom_line(aes(year_id,mx, col=state))
```



