---
title: "merge code"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
setwd(~/Dropbox/Harvard_Masters/Semester_Work/Fall_2017/BST260_DataScience/project)
```

## uploading data

```{r}
Alaska <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_ALASKA_Y2017M05D19.csv", header=TRUE, sep=",")
Alabama <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_ALABAMA_Y2017M05D19.csv", header=TRUE, sep=",")
Arizona <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_ARIZONA_Y2017M05D19.csv", header=TRUE, sep=",")
Arkansas <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_ARKANSAS_Y2017M05D19.csv", header=TRUE, sep=",")
California <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_CALIFORNIA_Y2017M05D19.csv", header=TRUE, sep=",")
COLORADO <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_COLORADO_Y2017M05D19.csv", header=TRUE, sep=",")
CONNECTICUT <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_CONNECTICUT_Y2017M05D19.csv", header=TRUE, sep=",")
DELAWARE <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_DELAWARE_Y2017M05D19.csv", header=TRUE, sep=",")
DC <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_DISTRICT_OF_COLUMBIA_Y2017M05D19.csv", header=TRUE, sep=",")
FLORIDA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_FLORIDA_Y2017M05D19.csv", header=TRUE, sep=",")
GEORGIA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_GEORGIA_Y2017M05D19.csv", header=TRUE, sep=",")
HAWAII <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_HAWAII_Y2017M05D19.csv", header=TRUE, sep=",")
IDAHO <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_IDAHO_Y2017M05D19.csv", header=TRUE, sep=",")
ILLINOIS <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_ILLINOIS_Y2017M05D19.csv", header=TRUE, sep=",")
INDIANA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_INDIANA_Y2017M05D19.csv", header=TRUE, sep=",")
IOWA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_IOWA_Y2017M05D19.csv", header=TRUE, sep=",")
KANSAS <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_KANSAS_Y2017M05D19.csv", header=TRUE, sep=",")
KENTUCKY <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_KENTUCKY_Y2017M05D19.csv", header=TRUE, sep=",")
LOUISIANA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_LOUISIANA_Y2017M05D19.csv", header=TRUE, sep=",")
MAINE <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_MAINE_Y2017M05D19.csv", header=TRUE, sep=",")
MARYLAND <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_MARYLAND_Y2017M05D19.csv", header=TRUE, sep=",")
MASSACHUSETTS <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_MASSACHUSETTS_Y2017M05D19.csv", header=TRUE, sep=",")
MIGHIGAN <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_MICHIGAN_Y2017M05D19.csv", header=TRUE, sep=",")
MINNESOTA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_MINNESOTA_Y2017M05D19.csv", header=TRUE, sep=",")
MISSISSIPPI <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_MISSISSIPPI_Y2017M05D19.csv", header=TRUE, sep=",")
MISSOURI <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_MISSOURI_Y2017M05D19.csv", header=TRUE, sep=",")
MONTANA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_MONTANA_Y2017M05D19.csv", header=TRUE, sep=",")
NEBRASKA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_NEBRASKA_Y2017M05D19.csv", header=TRUE, sep=",")
NEVADA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_NEVADA_Y2017M05D19.csv", header=TRUE, sep=",")
NEWHAMPSHIRE <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_NEW_HAMPSHIRE_Y2017M05D19.csv", header=TRUE, sep=",")
NEWJERSEY <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_NEW_JERSEY_Y2017M05D19.csv", header=TRUE, sep=",")
NEWMEXICO <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_NEW_MEXICO_Y2017M05D19.csv", header=TRUE, sep=",")
NEWYORK <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_NEW_YORK_Y2017M05D19.csv", header=TRUE, sep=",")
NORTHCAROLINA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_NORTH_CAROLINA_Y2017M05D19.csv", header=TRUE, sep=",")
NORTHDAKOTA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_NORTH_DAKOTA_Y2017M05D19.csv", header=TRUE, sep=",")
OHIO <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_OHIO_Y2017M05D19.csv", header=TRUE, sep=",")
OKLAHOMA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_OKLAHOMA_Y2017M05D19.csv", header=TRUE, sep=",")
OREGON <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_OREGON_Y2017M05D19.csv", header=TRUE, sep=",")
PENNSYLVANIA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_PENNSYLVANIA_Y2017M05D19.csv", header=TRUE, sep=",")
RHODEISLAND <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_RHODE_ISLAND_Y2017M05D19.csv", header=TRUE, sep=",")
SOUTHCAROLINA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_SOUTH_CAROLINA_Y2017M05D19.csv", header=TRUE, sep=",")
SOUTHDAKOTA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_SOUTH_DAKOTA_Y2017M05D19.csv", header=TRUE, sep=",")
TENNESSEE <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_TENNESSEE_Y2017M05D19.csv", header=TRUE, sep=",")
TEXAS <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_TEXAS_Y2017M05D19.csv", header=TRUE, sep=",")
UTAH <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_UTAH_Y2017M05D19.csv", header=TRUE, sep=",")
VERMONT <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_VERMONT_Y2017M05D19.csv", header=TRUE, sep=",")
VIRGINIA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_VIRGINIA_Y2017M05D19.csv", header=TRUE, sep=",")
WASHINGTON <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_WASHINGTON_Y2017M05D19.csv", header=TRUE, sep=",")
WESTVIRGINIA <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_WEST_VIRGINIA_Y2017M05D19.csv", header=TRUE, sep=",")
WISCONSIN <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_WISCONSIN_Y2017M05D19.csv", header=TRUE, sep=",")
WYOMING <- read.csv(file="IHME_USA_COUNTY_MORTALITY_RATES_1980_2014_WYOMING_Y2017M05D19.csv", header=TRUE, sep=",")
```

# merge data
```{r}
AllMortality <- rbind(Alaska, Alabama, Arizona, Arkansas, California, COLORADO, CONNECTICUT, DELAWARE, DC, FLORIDA, 
                      GEORGIA, HAWAII, IDAHO, ILLINOIS, INDIANA, IOWA, KANSAS, KENTUCKY, LOUISIANA, MAINE, 
                      MASSACHUSETTS, MARYLAND, MIGHIGAN, MINNESOTA, MISSISSIPPI, MISSOURI, MONTANA, NEBRASKA, 
                      NEVADA, NEWHAMPSHIRE, NEWYORK, NEWJERSEY, NEWMEXICO, NORTHCAROLINA, NORTHDAKOTA, OHIO, 
                      OKLAHOMA, OREGON, PENNSYLVANIA, RHODEISLAND, SOUTHCAROLINA, SOUTHDAKOTA, TENNESSEE, TEXAS, 
                      UTAH, VERMONT, VIRGINIA, WASHINGTON, WESTVIRGINIA, WISCONSIN, WYOMING) #merge all 51 states

AllMortality <- dplyr::filter(AllMortality, year_id >= 2010) # keep only data from 2010 - 2014
save(AllMortality, file="AllMortality.Rda")
```


# Load LE data
```{r}
setwd(~/Dropbox/Harvard_Masters/Semester_Work/Fall_2017/BST260_DataScience/FinalProject/finalproject/raw_data)
le2014 <- read.csv(file="le_2014_IHME.csv", header=TRUE, sep=",")
```

